config/routes.rb
Watet::Application.routes.draw do
	match "/auth/:provider/callback" => "sessions#create"
	match "/signout" => "sessions#signout", :as => :signout
	resources :users, :only => [:show] do
		resources :products, :except => [:index, :new, :show] do
		  collection do
		    post "sendlist"
		  end
		end
	end

 
  match "edit/:id" => "products#edit"
  match "destroy/:id" => "products#destroy"
  match "/products/update" => "products#update"
  match "show/:id" => "users#show"
  match "profile/:id" => "users#profile"
  match "product_profile/:id" => "users#product_profile"
  match "product_friend_profile/:id" => "users#product_friend_profile"

  match "add_wish/:id" => "users#add_wish"
  post "/users/:id" =>"users#add_wish"
  match "/terms" =>"users#terms"
  match "/terms_and_conditions" =>"products#terms_and_conditions"
  match  "/users/show" => "users#show"
  match  "/products/ordering_list/:id" => "products#ordering_list"
  match "/contact_us" => "products#contact_us"
   match "/products/contact_us_user" => "products#contact_us_user"

  match '/:locale' => 'users#show'
  match '/:locale' => 'users#add_wish'
  match '/:locale' => "products#edit"
  match '/:locale' => 'home#index'
scope "(:locale)", :locale => /en|sd|pl|fn|rs/ do
 resources :users
end

	get "home/index"

  match "users_product_list/:id" => "webservices#users_product_list"
  match "users_friend_list/:id" => "webservices#users_friend_list"

  match "show_list/:id" => "webservices#show_list"
  match "profile_product/:id" => "webservices#profile_product"
  match "product_edit/:id" => "webservices#product_edit"
  match "product_delete/:id" => "webservices#product_delete"
  match "add_product/:id" => "webservices#add_product"
  match "friend_products_list/:id" => "webservices#friend_products_list"
  match "friend_product_profile/:id" => "webservices#friend_product_profile"
  match "product_update/:id" => "webservices#product_update"

  root :to => 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
        validates :email, :uniqueness => true
	has_many :products, :dependent => :destroy
	has_many :auth_services, :dependent => :destroy

	def self.create_with_omniauth(info)
		create(:name => info[:name])
	end
end

app/controllers/users_controller.rb
require 'net/http'
require 'uri'
require 'open-uri'
require 'cgi'

class UsersController < ApplicationController
	def show
		 @user = User.find(params[:id])
     @products = Product.where(:user_id=>params[:id])
     @pro_order = @products.find(:all , :order => "order_id")
     @friends = []
        if session['fb_token'] != nil then
            fb_friends = ActiveSupport::JSON.decode(open(URI.encode("https://graph.facebook.com/me/friends?access_token=#{session['fb_token']}")))['data']
            @friends = fb_friends.collect { |f| AuthService.find_by_provider_and_uid('facebook', f['id']) }.compact
        end
      respond_to do |format|
      	format.html
        format.json { render :json => [@user, @friends] }
      end
	end

  def profile
      @user = User.find_by_id(session[:user_id])
      @product = Product.find(params[:id])
  end

  def add_wish
      @user = User.find(params[:id])
      @products = Product.where(:user_id=>params[:id].last)
      @product_order = Product.last
  end

  def trems
  end

  def product_profile
     @friends_product = Product.find_all_by_user_id(params[:id])
  end

  def product_friend_profile
     @friends_prod_profile = Product.find_by_id(params[:id])
     @user_name = User.find_by_id(@friends_prod_profile.user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/add_wish.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
var geocoder = new google.maps.Geocoder();

function geocodePosition(pos) {
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      updateMarkerAddress(responses[0].formatted_address);
    } else {
      updateMarkerAddress('Cannot determine address at this location.');
    }
  });
}

function updateMarkerStatus(str) {

}

function updateMarkerPosition(latLng) {

  $("#product_lat").val(latLng.lat());
  $("#product_lng").val(latLng.lng());

}

function updateMarkerAddress(str) {

}

function initialize() {
  var latLng = new google.maps.LatLng(50.534, 4.62622);
  var map = new google.maps.Map(document.getElementById('mapCanvas'), {
    zoom: 8,
    center: latLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
  var marker = new google.maps.Marker({
    position: latLng,
    title: 'Point A',
    map: map,
    draggable: true
  });

  // Update current position info.
  updateMarkerPosition(latLng);
  geocodePosition(latLng);

  // Add dragging event listeners.
  google.maps.event.addListener(marker, 'dragstart', function() {
    updateMarkerAddress('Dragging...');
  });

  google.maps.event.addListener(marker, 'drag', function() {
    updateMarkerStatus('Dragging...');
    updateMarkerPosition(marker.getPosition());
  });

  google.maps.event.addListener(marker, 'dragend', function() {
    updateMarkerStatus('Drag ended');
    geocodePosition(marker.getPosition());
  });
}

// Onload handler to fire off the app.
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<script type="text/javascript">
function validate_form(id){
var product_name=document.getElementById('product_name').value;
var product_descripton=document.getElementById('product_descripton').value;
var product_images=document.getElementById('product_images').value;

document.getElementById("name").innerHTML="";
document.getElementById("description").innerHTML="";
document.getElementById("product_images").innerHTML="";


var msg='false';
if(product_name==''){
msg='true';
document.getElementById("name").innerHTML="Enter your wish";
document.getElementById("product_name").focus();
}
if(product_descripton==''){
msg='true';
document.getElementById("description").innerHTML="Enter description about your wish ";
document.getElementById("product_descripton").focus();
}
if(product_images==''){
msg='true';
document.getElementById("image").innerHTML="Please upload image of your wish ";
document.getElementById("product_images").focus();
}

if(msg=='false')
return true;
else
return false;
}
</script>


<p style="text-align:right">
	<%= current_user.name %>
	<%= link_to "Sign out", :signout %>
</p>

  <div class="adminsales">
    <div id="add-deal-location" >
      <span class="bus_back"><%= link_to 'Back', :controller => 'users', :action => 'show', :id => current_user.id %></span>
<h1>GREAT TO HAVE <% if current_user.id != @user.id then %> for <%= @user.name %> <% end %></h1>

		<ul>
			<table style="text-align:left">
				<% if (current_user.id == @user.id) then %>
					<tr>
						<%= form_for([@user, Product.new],:html => {:multipart => true},:html=>{:onSubmit=>"return validate_form(this);"}) do |f| %>
                                        <label><%= t :Name%></label>
                                         <div class="clear"></div>
                                         <span id="name" style="color:#ee0000;"></span>
                                         <div class="clear"></div>
							<%= f.text_field :name %>
                                                       <% begin %>

                                                        <%= f.hidden_field :order_id, :value=>@product_order.order_id%>
                                                        <% rescue %>
                                                        <% end %>


                                                       <div class="clear"></div>
                                                        <label><%= t :Description%></label>
                                                         <div class="clear"></div>
                                                          <span id="description" style="color:#ee0000;"></span>
                                                          <div class="clear"></div>
                                                        <%= f.text_area :descripton  %>
                                                          <div class="clear"></div>
                                                          <label><%=t :Select_Wish_Date%></label>
                                                              <div class="clear"></div>
                                                              <%= f.date_select :wish_date, :order => [:day, :month, :year]%>
                                                               <div class="clear"></div>
                                                             <div class="clonedInput" id="input1">

                                                        <label><%=t :Upload_Images%></label>
                                                         <div class="clear"></div>
                                                         <div class="file">
                                                           <span id="image" style="color:#ee0000;"></span>
                                                           <div class="clear"></div>
                                                      <%=f.file_field :images%>
                                                      <%=f.file_field :images1%>
                                                      <%=f.file_field :images2%>
                                                      <%=f.file_field :images3%>
                                                         </div>

                                                         </div>
                                                        <div class="clear"></div>

                                                             <label><%=t :Select_Location%></label>
                                                              <div class="clear"></div>
                                                         <div class="maps" id="mapCanvas"></div>
                                                           <%= f.hidden_field :lat, :value=>"" %>
                                                            <%= f.hidden_field :lng, :value=>"" %>
                                                          <div class="clear"></div>

							<td class="actions"><%= f.submit "Submit"%></td>
						<% end %>
					</tr>
				<% end %>

				<%= render @user.products.order("created_at DESC") %>
			</table>
		</ul>
    </div>
  </div>

app/views/users/product_friend_profile.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
var geocoder = new google.maps.Geocoder();

function geocodePosition(pos) {
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      updateMarkerAddress(responses[0].formatted_address);
    } else {
      updateMarkerAddress('Cannot determine address at this location.');
    }
  });
}



function updateMarkerStatus(str) {

}

function updateMarkerPosition(latLng) {

  $("#product_lat").val(latLng.lat());
  $("#product_lng").val(latLng.lng());


}

function updateMarkerAddress(str) {

}

function initialize() {
  var latLng = new google.maps.LatLng(<%=  @friends_prod_profile.lat%>, <%= @friends_prod_profile.lng%>);
  var map = new google.maps.Map(document.getElementById('mapCanvas'), {
    zoom: 8,
    center: latLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
  var marker = new google.maps.Marker({
    position: latLng,
    title: 'Point A',
    map: map,
    draggable: true
  });

  // Update current position info.
  updateMarkerPosition(latLng);
  geocodePosition(latLng);

  // Add dragging event listeners.
  google.maps.event.addListener(marker, 'dragstart', function() {
    updateMarkerAddress('Dragging...');
  });

  google.maps.event.addListener(marker, 'drag', function() {
    updateMarkerStatus('Dragging...');
    updateMarkerPosition(marker.getPosition());
  });

  google.maps.event.addListener(marker, 'dragend', function() {
    updateMarkerStatus('Drag ended');
    geocodePosition(marker.getPosition());
  });
}

// Onload handler to fire off the app.
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<p style="text-align:right">
	<%= current_user.name %>
	<%= link_to "Sign out", :signout %>
</p>
  <div class="adminsales">
    <div id="add-deal-location">
      <span class="bus_back"><%= link_to 'Back', :controller => 'users', :action => 'show', :id =>current_user.id %></span>
  <label><%=t :User_Name%>:</label>&nbsp;&nbsp;<b><%=@user_name.name%></b>
  <div class="clear"></div>
<label><%= t :Product_Name%>:</label>&nbsp;&nbsp;<b><%=@friends_prod_profile.name%></b>
<div class="clear"></div>
<label><%= t :Description%>:</label><div class="clear"></div><b> <textarea id="txt_ar"><%=@friends_prod_profile.descripton%></textarea></b>
<div class="clear"></div>
  <label><%= t :Your_Wish_Complition_Date%>:</label>&nbsp;&nbsp;<b><%=@friends_prod_profile.wish_date%></b>
  <div class="clear"></div>
  <label><%= t :Location%>:</label><br/><div class="maps" id="mapCanvas"></div>
  <div class="clear"></div>
<label><%= t :Your_wish_Images%></label><br/><%= image_tag  @friends_prod_profile.images,  :size=> "200x200"%>
<%= image_tag  @friends_prod_profile.images1,  :size=> "200x200"%>
<%= image_tag  @friends_prod_profile.images2,  :size=> "200x200"%>
<%= image_tag  @friends_prod_profile.images3,  :size=> "200x200"%>
</div>
</div>

app/views/users/product_profile.html.erb
<p style="text-align:right">
	<%= current_user.name %>
	<%= link_to "Sign out", :signout %>
</p>
 <div class="adminsales">
    <div id="add-deal-location" >
<span class="bus_back"><%= link_to 'Back', :controller => 'users', :action => 'show', :id => current_user.id %></span>

<p class="caps"><%= t :Your_friends_wish_to_have%> </p>
<div id="test-list-category">
<div class="heading">
<ul>
<li class="first"><%=t :Name%></li>
<li class="middle"><%= t :Wish_Complition_Date%></li>
</ul>
</div>
<ul id="test-list" class="ui-sortable">
<% @friends_product.each do |p| %>

                    <li id="listItem_">
		    <div class="listname">
	            <img width="16" height="16" class="handle" alt="move" src="/images/arrow.png"/>
                    <%= link_to p.name, {:action => 'product_friend_profile', :controller => "users",:id => p.id} %></div>
		   <div class="listdate"><%= p.wish_date%></div>
		   </li>
<%end%>

</ul>

</div>
    </div>
 </div>

app/views/users/profile.html.erb
<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
var geocoder = new google.maps.Geocoder();

function geocodePosition(pos) {
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      updateMarkerAddress(responses[0].formatted_address);
    } else {
      updateMarkerAddress('Cannot determine address at this location.');
    }
  });
}



function updateMarkerStatus(str) {

}

function updateMarkerPosition(latLng) {

  $("#product_lat").val(latLng.lat());
  $("#product_lng").val(latLng.lng());


}

function updateMarkerAddress(str) {

}

function initialize() {
  var latLng = new google.maps.LatLng(<%=@product.lat%>, <%= @product.lng%>);
  var map = new google.maps.Map(document.getElementById('mapCanvas'), {
    zoom: 8,
    center: latLng,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  });
  var marker = new google.maps.Marker({
    position: latLng,
    title: 'Point A',
    map: map,
    draggable: true
  });

  // Update current position info.
  updateMarkerPosition(latLng);
  geocodePosition(latLng);

  // Add dragging event listeners.
  google.maps.event.addListener(marker, 'dragstart', function() {
    updateMarkerAddress('Dragging...');
  });

  google.maps.event.addListener(marker, 'drag', function() {
    updateMarkerStatus('Dragging...');
    updateMarkerPosition(marker.getPosition());
  });

  google.maps.event.addListener(marker, 'dragend', function() {
    updateMarkerStatus('Drag ended');
    geocodePosition(marker.getPosition());
  });
}

// Onload handler to fire off the app.
google.maps.event.addDomListener(window, 'load', initialize);
</script>
<p style="text-align:right">
	<%= current_user.name %>
	<%= link_to "Sign out", :signout %>
</p>
  <div class="adminsales">
    <div id="add-deal-location">
      <span class="bus_back"><%= link_to 'Back', :controller => 'users', :action => 'show', :id => current_user.id %></span>
  <label><%=t :User_Name%>:</label>&nbsp;&nbsp;<b><%=@user.name%></b>
  <div class="clear"></div>
<label><%= t :Product_Name%>:</label>&nbsp;&nbsp;<b><%=@product.name%></b>
<div class="clear"></div>
<label><%= t :Description%>:</label><div class="clear"></div><b> <textarea id="txt_ar"><%=@product.descripton%></textarea></b>
<div class="clear"></div>
  <label><%= t :Your_Wish_Complition_Date%>:</label>&nbsp;&nbsp;<b><%=@product.wish_date%></b>
  <div class="clear"></div>
  <label><%= t :Location%>:</label><br/><div class="maps" id="mapCanvas"></div>
  <div class="clear"></div>
<label><%= t :Your_wish_Images%></label><br/><%= image_tag  @product.images,  :size=> "200x200"%>
<%= image_tag  @product.images1,  :size=> "200x200"%>
<%= image_tag  @product.images2,  :size=> "200x200"%>
<%= image_tag  @product.images3,  :size=> "200x200"%>
</div>
</div>

app/views/users/show.html.erb
<script type="text/javascript">
  function confirmValidate(){
var Check = confirm("Are you sure you want to delete this?");
if(Check){
    return true;
}else{
    return false;
}

}
</script>

<span class="bus_back1">
<form action="#" method="get">
  <select name="locale" onchange="this.form.submit()">
    <option>Select Language</option>
    <option value="en">English</option>
    <option value="rs">Russian</option>
    <option value="fn">Finnish</option>
    <option value="sd">Swedish</option>
    <option value="pl">Polish</option>
   </select>
</form></span>
<p style="text-align:right"><%= current_user.name %><%= link_to "Sign out", :signout %></p>
<div class="adminsales">
    <div id="add-deal-location" >
      <div style="color:#ee0000;"><%= flash[:notice] %></div>
        <div class="actions"><span class="bus_back"><%= button_to 'Add Wish', {:action => 'add_wish', :controller => "users", :id=>session[:user_id] } %></span></div>
          <pre><div id="info"></div></pre>
<script type="text/javascript" src="/js/jquery-1.js"></script>
<script type="text/javascript" src="/js/jquery-ui-personalized-1.js"></script>
<script type="text/javascript">
    // When the document is ready set up our sortable with it's inherant function(s)
    $(document).ready(function() {

        $("#test-list").sortable({
            handle : '.handle',
            update : function () {
            var order = $('#test-list').sortable('serialize');
                $("#info").load("/products/ordering_list/"+order);
            }
        });
    });
</script>
 <p class="caps"><%= t :Your_friends_wish_to_have%> </p>
<div id="test-list-category">
<div class="heading">
<ul>
<li class="first"><%=t :Name%></li>
<li class="middle"><%= t :Wish_Complition_Date%></li>
<li class="last"><%= t :Action %></li>
</ul>
</div>
<ul id="test-list" class="ui-sortable">
    <% @pro_order.each do |i|  %>
          <li id="listItem_<%= i.id%>">
	       <div class="listname">
	          <img width="16" height="16" class="handle" alt="move" src="/images/arrow.png"/>
                  <%= link_to i.name, {:action => 'profile', :controller => "users",:id => i.id} %></div>
		   <div class="listdate"><%= i.wish_date%></div>
		   <div class="listaction"> <%= link_to "Edit", {:action => 'edit', :controller => "products", :id => i.id} %><span>/</span><%= link_to "Delete", {:action => 'destroy', :controller => "products",:id => i.id}, :onclick=>" return confirmValidate();"%></div>
           </li>
    <%end%>
</ul>
</div>
<p class="caps"><h3><b><%= t :Show_Friend_List%></b> </h3> </p>
<div id="test-list-category">
    <div class="heading">
      <ul>
        <li class="first"><%=t :Name%></li>
        <li class="last"><%= t :Email %></li>
      </ul>
</div>
<ul id="test-list" class="ui-sortable">
      <% @friends.each do |f| %>
             <li id="listItem_">
               <div class="listname">
	       <img width="16" height="16" class="handle" alt="move" src="/images/arrow.png"/>
               <%= link_to f.uname, {:action => 'product_profile', :controller => "users",:id => f.id} %></div>
               <div class="listdate1"><%= f.uemail%></div>
            </li>
      <%end%>

</ul>
<div class="emailbox">
  <h3><%=t :Send_the_list_via_email%></h3>
  <% if current_user.id == @user.id then %>
			<%= form_tag(sendlist_user_products_path(current_user)) do %>
                          <div class="clear"></div>
                        <span id="email" style="color:#ee0000;"></span>
                       <div class="clear"></div>
  				<%= text_field_tag(:email) %>
                        <div class="actions">
  				<%= submit_tag("Send") %>
                        </div>
			<% end %>
			<br/>
		<% end %>
        </div>
      </div>
    </div>
</div>

app/views/users/terms.html.erb
  <div class="adminsales">
    <div id="add-deal-location" >
    <div id="privacy">
         <div class="content">

         <h2>watet.com, PRIVACY POLICY</h2>
         <h4>Terms of Use Agreement</h4>

         	<p>We at watet know that our users ("you," "your," or "yourself") care about how your personal information is used and shared, and we 				take your privacy seriously. Please read the following to learn more about our Privacy Policy. By visiting or using the www.watet.com website and domain name, any other linked pages, features, content, mobile applications, and any other services we offer from time to time in connection with any of the foregoing (collectively, the "Website"), you agree to the practices and policies set forth in this Privacy Policy, and you hereby acknowledge and consent to our collection, use, and sharing of your information as described in this Privacy Policy. Capitalized terms that are not defined in this Privacy Policy have the meaning given to them in our Terms of Use.</p>

            <b>I. WHAT DOES THIS PRIVACY POLICY COVER?</b>

            <p>This Privacy Policy covers our treatment of personally identifiable information ("Personal Information") that we gather when you are accessing or using our Website. This policy does not apply to the practices of companies that we do not own or control, or to individuals that we do not employ or manage, even if you have accessed the websites or services of those companies through our Website.</p>
            <p>We do not knowingly collect or solicit personal information from anyone under the age of 13 or knowingly allow such persons to register for the Services (as that term is defined in our Terms of Use). If you are under 13, please do not attempt to register for the Services or send any information about yourself to us, including your name, address, telephone number, or email address. No one under age 13 may provide any personal information to us or on the Services. If we learn that we have collected personal information from a child under age 13 without verification of parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 13, please contact us at <span><a href="mailto:support@watet.com">support@watet.com</a></span>.</p>

            <b>II. WHAT INFORMATION DOES watet COLLECT?</b>

            <p>We gather various types of Personal Information from our users, as explained more fully below. We may use this Personal Information to, among other things, personalize and improve our services, allow our users to set up a user account and profile, contact users, fulfill your requests for certain products and services, analyze how users utilize the Website, or as otherwise set forth in this Privacy Policy. We may share certain types of Personal Information with third parties (as described in this Section and in Section III below). We collect the following types of information:</p>

            <b>A. Information You Provide to Us:</b>

            <p class="sub">We receive and store any information you knowingly provide to us. For example, we collect Personal Information such as your name, username, phone number, credit card and other billing information, email address, shipping address, and your friends' email addresses (which we will only use in order to invite them to use the Service). We may also collect information you supply to us regarding your personal preferences and interests. You can choose not to provide us with any or all of the information we specify or request, but then you may not be able to register with us or to take advantage of some or all of our features.</p>

            <p class="sub">We may anonymize your Personal Information so that you cannot be individually identified and provide that anonymized information to our partners. For example, we allow advertisers to choose the demographic information of users who will see their advertisements and you agree that we may use any of the information we have collected from you in non-personally identifiable form to allow our advertisers to select the appropriate audience for those advertisements. We might use the fact you have purchased or inquired about a certain brand of apparel, for instance, to show you advertisements for the company that sells that brand, but we will not tell that company who you are.</p>
            <b>B. Information Collected Automatically:</b>

            <ul>
            <li>Whenever you interact with our Website, we automatically receive and record information on our server logs from your browser including your IP address, "cookie" information, and the page you requested. "Cookies" are identifiers we transfer to your computer or device that allow us to recognize your browser or device and tell us how and when pages in our Website are visited and by how many people. You may be able to change the preferences on your browser or device to prevent or limit your computer's or device's acceptance of cookies, but doing so may prevent you from taking advantage of our Website's best features. Our advertising partners may transmit cookies to your computer or device when you click on ads that appear on our site. This Privacy Policy does not cover cookies delivered to you by any of our advertisers.</li>
               <li>When we collect usage information (such as the numbers and frequency of visitors to the Website), we only use such data in aggregate form, in a manner that assures your anonymity. We may provide this aggregate usage information to our partners; our partners may use such information to understand how often and in what ways people use our Website, so that our partners, too, can endeavor to provide you with an optimal online experience.</li>
            </ul>

         </div>
	</div>








<%= form_for(@trems, :as =>:users, :url =>"/terms_and_conditions",:id => session[:user_id], :method =>"post") do |f| %>
<div class ="clear"></div>
 <span id="trems1" style="color:#ee0000;"></span>
<h4><%= f.check_box :terms %>I agree tothese conditions</h4>
<%= f.hidden_field :id, :value => session[:user_id]%>
<%=session[:user_id].inspect%>
<div class= "actions" align ="center">
<%= f.submit "Submit"%>
</div>

<%end%>

       </div>
       </div>